import schemaConfig from "./schemaValidator";

export enum NETWORK {
  MTN = "01",
  GLO = "02",
  "9MOBILE" = "03",
  AIRTEL = "04",
}

export enum DATA_TYPE {
  SME = "SME",
  CORPORATE = "CORPORATE",
  DIRECT = "DIRECT",
}

export default {
  ...schemaConfig,
  networks: [
    {
      name: "MTN",
      id: NETWORK["MTN"],
    },
    {
      name: "GLO",
      id: NETWORK["GLO"],
    },
    {
      name: "9MOBILE",
      id: NETWORK["9MOBILE"],
    },
    {
      name: "AIRTEL",
      id: NETWORK["AIRTEL"],
    },
  ],
  airtime: [
    {
      network: NETWORK["MTN"],
      discount: 3,
    },
    {
      network: NETWORK["GLO"],
      discount: 7.5,
    },
    {
      network: NETWORK["9MOBILE"],
      discount: 6,
    },
    {
      network: NETWORK["AIRTEL"],
      discount: 3,
    },
  ],
  internet: {
    mtn: [
      {
        amount: 50,
        charged: 18,
        plan: "50 MB",
        planCode: "50.00",
        duration: " 30 days",
        type: DATA_TYPE["CORPORATE"],
      },
      {
        amount: 150,
        charged: 46,
        plan: "150 MB",
        planCode: "150.00",
        duration: " 30 days",
        type: DATA_TYPE["CORPORATE"],
      },
      {
        amount: 250,
        charged: 74,
        plan: "250 MB",
        planCode: "250.00",
        duration: " 30 days",
        type: DATA_TYPE["CORPORATE"],
      },
      {
        amount: 500,
        charged: 136,
        plan: "500 MB",
        planCode: "500.0",
        duration: " 30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 1000,
        charged: 273,
        plan: "1 GB",
        planCode: "1000.0",
        duration: " 30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 1000,
        charged: 546,
        plan: "2 GB",
        planCode: "2000.0",
        duration: " 30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 1000,
        charged: 819,
        plan: "3 GB",
        planCode: "3000.0",
        duration: " 30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 1000,
        charged: 1365,
        plan: "5 GB",
        planCode: "5000.0",
        duration: " 30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 1000,
        charged: 4040,
        plan: "15 GB",
        planCode: "15000.00",
        duration: " 30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 1000,
        charged: 5510,
        plan: "20 GB",
        planCode: "20000.00",
        duration: " 30 days",
        type: DATA_TYPE["CORPORATE"],
      },
      {
        amount: 1000,
        charged: 6900,
        plan: "25 GB",
        planCode: "25000.00",
        duration: " 30 days",
        type: DATA_TYPE["CORPORATE"],
      },
      {
        amount: 1000,
        charged: 13650,
        plan: "50 GB",
        planCode: "50000.00",
        duration: " 30 days",
        type: DATA_TYPE["CORPORATE"],
      },
      {
        amount: 1000,
        charged: 26800,
        plan: "100 GB",
        planCode: "100000.00",
        duration: " 30 days",
        type: DATA_TYPE["CORPORATE"],
      },
    ],
    glo: [
      {
        amount: 0,
        charged: 52,
        plan: "200 MB",
        planCode: "200",
        duration: "14 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 121,
        plan: "500 MB",
        planCode: "500",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 240,
        plan: "1 GB",
        planCode: "1000",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 480,
        plan: "2 GB",
        planCode: "2000",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 720,
        plan: "3 GB",
        planCode: "3000",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 1200,
        plan: "5 GB",
        planCode: "5000",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 2400,
        plan: "10 GB",
        planCode: "10000",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 96,
        plan: "105 MB",
        planCode: "105.01",
        duration: "1 day",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 192,
        plan: "350 MB",
        planCode: "350.01",
        duration: "1 day",
        type: DATA_TYPE["DIRECT"],
      },
    ],
    airtel: [
      {
        amount: 0,
        charged: 26,
        plan: "100 MB",
        planCode: "100",
        duration: "7 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 70,
        plan: "300 MB",
        planCode: "300",
        duration: "7 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 114,
        plan: "500 MB",
        planCode: "500",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 215,
        plan: "1 GB",
        planCode: "1000",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 430,
        plan: "2 GB",
        planCode: "2000",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 1075,
        plan: "5 GB",
        planCode: "5000",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 2150,
        plan: "10 GB",
        planCode: "10000",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 3225,
        plan: "15 GB",
        planCode: "15000",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 4300,
        plan: "20 GB",
        planCode: "20000",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 96.03,
        plan: "100 MB",
        planCode: "99.00",
        duration: "1 day",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 193.06,
        plan: "200 MB",
        planCode: "199.03",
        duration: "3 days",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 290.05,
        plan: "350 MB",
        planCode: "299.02",
        duration: "7 days",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 484.03,
        plan: "750 MB",
        planCode: "499.00",
        duration: "14 days",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 290.06,
        plan: "1 GB",
        planCode: "299.03",
        duration: "1 day",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 969.03,
        plan: "1.5 GB",
        planCode: "999.00",
        duration: "30 days",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 484.06,
        plan: "2 GB",
        planCode: "499.03",
        duration: "1 day",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 1163.03,
        plan: "2 GB",
        planCode: "1199.00",
        duration: "30 days",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 1454.04,
        plan: "3 GB",
        planCode: "1499.01",
        duration: "30 days",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 1939.03,
        plan: "4.5 GB",
        planCode: "1999.00",
        duration: "30 days",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 1454.06,
        plan: "6 GB",
        planCode: "1499.03",
        duration: "7 days",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 2424.04,
        plan: "6 GB",
        planCode: "2499.01",
        duration: "30 days",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 2909.05,
        plan: "8 GB",
        planCode: "2999.02",
        duration: "30 days",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 3879.04,
        plan: "11 GB",
        planCode: "3999.01",
        duration: "30 days",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 4849.03,
        plan: "15 GB",
        planCode: "4999.00",
        duration: "30 days",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 9699.03,
        plan: "40 GB",
        planCode: "9999.00",
        duration: "30 days",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 14549.03,
        plan: "75 GB",
        planCode: "14999.00",
        duration: "30 days",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 19399.05,
        plan: "110 GB",
        planCode: "19999.02",
        duration: "30 days",
        type: DATA_TYPE["DIRECT"],
      },
    ],
    "9mobile": [
      {
        amount: 0,
        charged: 11,
        plan: "50 MB",
        planCode: "50",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 18,
        plan: "100 MB",
        planCode: "100",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 46,
        plan: "300 MB",
        planCode: "300",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 79,
        plan: "500 MB",
        planCode: "500",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 140,
        plan: "1 GB",
        planCode: "1000",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 280,
        plan: "2 GB",
        planCode: "2000",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 420,
        plan: "3 GB",
        planCode: "3000",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 560,
        plan: "4 GB",
        planCode: "4000",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 700,
        plan: "5 GB",
        planCode: "5000",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 1400,
        plan: "10 GB",
        planCode: "10000",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 2100,
        plan: "15 GB",
        planCode: "15000",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 2800,
        plan: "20 GB",
        planCode: "20000",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 3500,
        plan: "25 GB",
        planCode: "25000",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 6500,
        plan: "50 GB",
        planCode: "50000",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 13000,
        plan: "100 GB",
        planCode: "100000",
        duration: "30 days",
        type: DATA_TYPE["SME"],
      },
      {
        amount: 0,
        charged: 467.5,
        plan: "500 MB",
        planCode: "500.01",
        duration: "30 days",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 935,
        plan: "1.5 GB",
        planCode: "1500.01",
        duration: "30 days",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 1122,
        plan: "2 GB",
        planCode: "2000.01",
        duration: "30 days",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 1870,
        plan: "4.5 GB",
        planCode: "4500.01",
        duration: "30 days",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 1402.5,
        plan: "7 GB",
        planCode: "3000.01",
        duration: "7 days",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 3740,
        plan: "11 GB",
        planCode: "11000.01",
        duration: "30 days",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 4675,
        plan: "15 GB",
        planCode: "15000.01",
        duration: "30 days",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 9350,
        plan: "40 GB",
        planCode: "40000.01",
        duration: "30 days",
        type: DATA_TYPE["DIRECT"],
      },
      {
        amount: 0,
        charged: 14025,
        plan: "75 GB",
        planCode: "75000.01",
        duration: "30 days",
        type: DATA_TYPE["DIRECT"],
      },
    ],
  },
};
